#Params from DOI: 10.1021/acs.jpcb.6b01870
#A Critical Comparison of Biomembrane Force Fields: Structure and Dynamics of Model DMPC, POPC, and POPE Bilayers
#TODO: add info from gromacs documentation!
MD_CONSTR=h-bonds
HT_CONSTR=h-bonds # default - same as MD
MD_RLIST=1.2
MD_RC=1.2
MD_RVDW=1.2

VDW_MOD=force-switch
VDW_SW=0.8 # TODO: maybe 0.8

MD_DC= # DispCorr
TAU_P_MD=5.0
TAU_T=0.5
TCOUPLMD=Nose-Hoover
PCOUPLMD=Parrinello-Rahman
#PCOUPLMD=Berendsen

#TAU_P=1 # 4 berendsen